import {ROUTES} from '../../constants';

const SEARCH_V2_ACTIONS = {
	TOURS_REQUESTED: 'SEARCH_V2_TOURS_REQUESTED',
	TOURS_SUCCESS: 'SEARCH_V2_TOURS_SUCCESS',
	TOURS_FAILED: 'SEARCH_V2_TOURS_FAILED',
	TOURS_UPDATE: 'SEARCH_V2_TOURS_UPDATE',

	FILTERS_SERVER_REQUESTED: 'FILTERS_SERVER_REQUESTED',
	FILTERS_SERVER_SUCCESS: 'FILTERS_SERVER_SUCCESS',
	FILTERS_SERVER_FAILED: 'FILTERS_SERVER_FAILED',

	FILTERS_CLIENTS_UPDATE: 'SEARCH_V2_FILTERS_CLIENTS_UPDATE',

	LINKS_GEO_UPDATE: 'SEARCH_V2_LINKS_GEO_UPDATE',

	SEARCH_PARAMS_UPDATE: 'SEARCH_V2_SEARCH_PARAMS_UPDATE',

	SEO_TEXT_REQUEST: 'SEARCH_V2_SEO_TEXT_REQUEST',
	SEO_TEXT_SUCCESS: 'SEARCH_V2_SEO_TEXT_SUCCESS',
};


export const ROUT_MAIN_PAGE = '/';
export const ROUT_SEARCH_MAIN = `/${ROUTES.Search}/*`;
export const ROUT_SEARCH_HOT_TOURS = `/${ROUTES.AllHotTours}/*`;
export const ROUT_SEARCH_HOTELS = '';



export default SEARCH_V2_ACTIONS;
